### ISSUE TITLE
[项目申请]: Cscan-Go

### ISSUE THREAD

**Issue by ifacker** [knownsec/404StarLink#100]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Cscan-Go

### 项目地址

https://github.com/ifacker/cscan-go

### 项目简介

Cscan-Go 一款主要用来平替 cscan(python版) 的，本人也很喜欢使用 cscan，但是无奈 python 版有一些局限性，在内网横向的时候，如果想要把 cscan 传到内网，就要考虑环境的问题了，所以有了 cscan 的 go 版本！

本程序目前刚开始开发，所以有些 cscan 原版的功能不是很全，但是我会把 cscan 原版的全部功能都加进去的，然后再加一些自己觉得好用的小细节和功能点，在今后的hw中，方便红队队员们使用。

### 项目亮点

1. 基本的端口扫描
2. 支持 IP、IP段、c段，三种格式的扫描方式
3. 端口输入支持范围输入
4. 导入 IP 文件同样支持 IP、IP段、c段，三种格式的扫描方式
5. 支持 socks5、http 代理，方便挂代理扫描，或者穿透到内网扫描
6. 扫描完端口之后，对于开放的端口，检测是否有 web 服务（并且检测到的结果终端输出显示的花里胡哨）
7. 只输出指定状态码的扫描结果的功能
8. 实现导出功能，支持 txt、csv 两种格式
9. 增加新选项，-nc 禁止暴力破解
10. 支持简单的暴力破解功能（内置简易字典，无需设置）
        支持 SSH 协议暴力破解
        支持 Mssql 协议暴力破解
        支持 Mysql 协议暴力破解
        支持 Ftp 协议暴力破解
        支持 Smb 协议暴力破解
        支持 Memcached 协议暴力破解
        支持 Mongodb 协议暴力破解
        支持 Oracle 协议暴力破解
        支持 Postgres 协议暴力破解
        支持 Redis 协议暴力破解

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
