### ISSUE TITLE
[项目申请]: CGraph 色丶图

### ISSUE THREAD

**Issue by ChunelFeng** [knownsec/404StarLink#101]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

CGraph

### 项目地址

https://github.com/ChunelFeng/CGraph

### 项目简介

 一个简单好用的、无任何三方依赖的、跨平台的、收录于awesome-cpp的、基于流图的并行计算框架

### 项目亮点

无第三方依赖的 DAG 调度框架。实现了依赖节点依次执行、无依赖节点并发执行的逻辑。可用于链路安全分段/分级排查工作，和窥孔优化领域。

项目结构清晰、文档齐全，不仅代码中包含关键注释，还有示例代码和讲解文章。

初学者可以通过该项目学到图调度方式、模块开发、模板编程、多线程编程、设计模式和通用算法的知识

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
