### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by wqreytuk** [knownsec/404StarLink#102]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

py135

### 项目地址

https://github.com/wqreytuk/py135

### 项目简介

传统的通过445端口进行内网横向移动的工具在内网越来越难以使用，因为很多主机445端口都无法访问，因此便有了本项目，通过135端口进行横向移动的工具

### 项目亮点

仅依赖135进行windows主机的命令执行，支持明文认证、hash认证和票据认证，同时支持真正意义的大文件的稳定上传和下载

完美躲过杀软检测，且回显速度相比同类工具更快，同时由于是使用python实现，天然具有跨平台的优越性

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
