### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by dark-kingA** [knownsec/404StarLink#103]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

superSearchPlus

### 项目地址

https://github.com/dark-kingA/superSearchPlus

### 项目简介

谷歌插件版本- superSearchPlus是聚合型信息收集插件，支持综合查询，资产测绘查询，信息收集 js敏感信息提取 注释资源扫描 目录扫描 整合了目前常见的资产测绘平台 同时支持数据导出

### 项目亮点

谷歌插件版本：https://github.com/dark-kingA/superSearchPlus
桌面端版本：https://github.com/dark-kingA/arsenalTools
桌面端 插件版 目前集成了主流信息收集相关api 等

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
