### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by Mob2003** [knownsec/404StarLink#104]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

rakshasa

### 项目地址

https://github.com/Mob2003/rakshasa

### 项目简介

rakshasa是一个使用Go语言编写的强大多级代理工具，专为实现多级代理，内网穿透而设计。

### 项目亮点

它可以在节点群里面任意两个节点之间转发TCP请求和响应，同时支持socks5代理，http代理，并且可以引入外部http、socks5代理池，自动切换请求IP。节点之间使用内置证书的TLS加密TCP通讯，再叠加一层自定义秘钥的AES加密，可以在所有Go支持的平台使用。可以在你所有的的Windows和Linux服务器上搭建节点并组成节点群网络。

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
