### ISSUE TITLE
[项目申请]: dperf

### ISSUE THREAD

**Issue by pengjianzhang** [knownsec/404StarLink#105]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

dperf

### 项目地址

https://github.com/baidu/dperf

### 项目简介

dperf 是一个100Gbps的网络性能与压力测试软件。国内多个知名安全厂商用dperf测试其防火墙。知名开源四层负载均衡DPVS在用dperf做性能测试，发布性能测试报告。

### 项目亮点

- 性能强大：
  - 基于 DPDK，使用一台普通 x86 服务器就可以产生巨大的流量：千万级的 HTTP 每秒新建连接数，数百Gbps的带宽，几十亿的并发连接数
- 统计信息详细：
  - 能够输出详细的统计信息，并且识别每一个丢包
- 使用场景丰富：
  - 可用于对四层负载均衡等四层网关进行性能压力测试、长稳测试
  - 可用于对云上虚拟机的网络性能进行测试
  - 可用于对网卡性能、CPU的网络报文处理能力进行测试
  - 压测场景下，可作为高性能的HTTP Server或HTTP Client单独使用

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
