### ISSUE TITLE
[项目申请]: unveilr

### ISSUE THREAD

**Issue by r3x5ur** [knownsec/404StarLink#106]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

unveilr

### 项目地址

https://github.com/r3x5ur/unveilr

### 项目简介

小程序反编译工具

### 项目亮点

提取小程序源代码，用于分析未授权接口等信息收集工作

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
