### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by codeyso** [knownsec/404StarLink#110]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

CodeTest

### 项目地址

https://github.com/codeyso/CodeTest

### 项目简介

一款常用测试脚本和漏洞扫描脚本的管理工具，方便运行。

### 项目亮点

1、统一脚本输出环境，进度条跟踪，可视化操作，解放控制台，点击执行。
2、支持脚本重载，项目内部自带简易编辑器，修改脚本后保存可实现"热更新"。
3、自带代理设置，使用HTTP或SOCKS代理和其他工具联动。具备收集免费代理功能，并一键开启代理切换。
4、支持常见空间搜索引擎，管理资产。
5、漏洞探测和利用分开运行，不包含其他恶意代码。
5、漏洞仓库存储探测到的地址，可分配不同的界面执行命令，支持一键探测存活和利用。
6、能发包测试，可由数据包根据模板生成脚本。
7、工具有笔记和异常日志，方便追踪问题。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
