### ISSUE TITLE
[项目申请]: wmiexec-Pro

### ISSUE THREAD

**Issue by XiaoliChan** [knownsec/404StarLink#111]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

wmiexec-Pro

### 项目地址

https://github.com/XiaoliChan/wmiexec-Pro

### 项目简介

基于原先第一个项目 [wmiexec-RegOut](https://github.com/XiaoliChan/wmiexec-RegOut) 以及 [WMIHACKER](https://github.com/rootclay/WMIHACKER) 的思路重写的wmiexec.py，在横向移动中可以基本可以不被杀软拦截

### 项目亮点

1、基本信息枚举模块，类似systeminfo
2、重写命令执行模块，命令结果存放在自行创建的wmi类里面
3、命令执行模块支持半交互式Shell
4、文件传输，支持大文件传输，不在通过注册表传输，而是通过wmi类进行数据存储
5、RDP模块，无需CMD命令，通过wmi类进行开/关 RDP
6、WinRM模块，无需CMD命令，通过wmi类进行开/关 WinRM
7、防火墙模块，滥用防火墙类，能通过指定端口去查找关联的防火墙规则，支持删除，启用，禁用指定的防火墙规则，能开启/关闭防火墙profile，全程无需CMD命令
8、日志模块，循环清除日志
9、服务模块，无需CMD命令，远程操作服务，包括创建
10、合并impacket官方的wmipersist.py执行vbs模块
11、远程RID劫持，无需落地EXE，Powershell脚本即可完成劫持，杀软无感，支持启用，禁用，备份，删除，恢复本地用户

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
