### ISSUE TITLE
[项目申请]: URLFinder

### ISSUE THREAD

**Issue by pingc0y** [knownsec/404StarLink#113]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

URLFinder

### 项目地址

https://github.com/pingc0y/URLFinder

### 项目简介

URLFinder是一款快速、全面、易用的页面信息提取工具

用于分析页面中的js与url,查找隐藏在其中的敏感信息或未授权api接口

### 项目亮点

- 输出结果支持 html、csv、json
- 通过yaml配置可高度自定义
- 实用性高，快速、全面、易用
- 长期维护更新

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！
