### ISSUE TITLE
[项目申请]: noterce

### ISSUE THREAD

**Issue by xiao-zhu-zhu** [knownsec/404StarLink#115]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

noterce

### 项目地址

https://github.com/xiao-zhu-zhu/noterce

### 项目简介

 一种另辟蹊径的免杀执行系统命令的木马 

### 项目亮点

使用公开笔记网站[https://note.ms做中间服务器，无需部署 VPS，通过笔记本的读写来实现作为被控端和控制端之间的流量传递载体。目前实测可过核晶和火绒

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
