### ISSUE TITLE
[项目申请]: Spring_All_Reachable

### ISSUE THREAD

**Issue by savior-only** [knownsec/404StarLink#116]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Spring_All_Reachable

### 项目地址

https://github.com/savior-only/Spring_All_Reachable

### 项目简介

Spring漏洞综合利用工具。

### 项目亮点

该项目主要是为了在日常工作中遇到spring漏洞可以快速验证利用，减少手动利用所消耗的时间，支持检测、回显、内存马，是红队攻防的一款利器。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
