### ISSUE TITLE
[项目申请]: SeaMoon

### ISSUE THREAD

**Issue by DVKunion** [knownsec/404StarLink#119]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Seamoon

### 项目地址

https://seamoon.dvkunion.cn (https://github.com/DVKunion/SeaMoon.git)

### 项目简介

月海(Sea Moon) 是一款 FaaS/BaaS 实现的 Serverless 云渗透工具集，致力于开启云原生的渗透模式。

月海之名取自于苏轼的《西江月·顷在黄州》，寓意月海取自于传统安全工具，用之于云，最终达到隐匿于海的效果。

说人话的总结，月海其实就是一款利用云函数来隐匿攻击行踪以及分布式处理扫描任务的集成工具，并期望成为云原生时代，云计算资源应用于安全渗透的抛砖引玉者，提供出更多利用的框架模式。

### 项目亮点

+ 随着云原生不断地推广，希望渗透测试也能够与时俱进，开启一个新的纪元。不论从测试的手段还是挖掘方向，都应该朝着时代发展的方向跟进。
+ 现有的大部分云函数利用止步于网络层(http/sock5/c2)，且大部分代理需要自行编写特定的Client端。
+ 现有项目模式较为松散，部署还是需要花费一些经历来理解和操作。而类似阿里云已经上升到serverless应用的层级，相应的部署方式和玩法更新颖。
+ 如果将这些项目比作是概念性工具，那么月海致力于打造的是一个较为成熟化的，能够快速简易应用的工具集产品。
+ 月海在传统云函数的利用上，实现了一个不需要vps的socks代理模式；目前基本实现了网络层4层功能，将逐步向安全应用层靠拢。
+ 月海希望能够抛砖引玉，提出一个简易的框架和模式，将现有的大部分可迁移至云端操作的攻击手段集成进来，最终达到随手拿来的一台崭新电脑，5分钟即可进入攻击状态(理想)。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
