### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by selinuxG** [knownsec/404StarLink#120]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Golin-cli

### 项目地址

https://github.com/selinuxG/Golin-cli

### 项目简介

基于Golang实现的轻量跨平台工具，不仅注重于"攻击"，更重视于"防护"。

### 项目亮点

- 无需配置任何环境，二进制文件即可运行。
- 内置多种设备类型按照三级等保要求，基于《GBT-28448》国标要求内置核查命令，适用于甲方风险自查。
- 支持端口扫描、协议识别、组件识别。
- 支持多种类型弱口令扫描。
- 支持子域名扫描，支持基于字典文件 DNS 碰撞以及 FOFA 调用、RapidDNS 调用。
- 支持web目录扫描，支持自定义状态码、代理、超时、User-Agent、返回 title、size 等信息。
- 支持 Windows 系统基线核查并生成报告。
- 以上内容均基于多线程，并可指定。
- 部分功能支持 web 平台使用。
- 总结：可风险自查，可资产收集。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
