### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by G3et** [knownsec/404StarLink#121]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Search_Viewer

### 项目地址

https://github.com/G3et/Search_Viewer

### 项目简介

一款空间测绘的信息收集工具，主要是gui界面化，会更方便的展示查询数据和导出数据等

### 项目亮点

工具目前集成了6个空间测绘平台，之后会继续添加其他平台，目前平台包含有：Fofa、Hunter鹰图、Shodan、360 quake、Zoomeye 钟馗之眼、censys

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
