### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by RuoJi6** [knownsec/404StarLink#122]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

HackerPermKeeper

### 项目地址

https://github.com/RuoJi6/HackerPermKeeper

### 项目简介

通过渗透拿到权限之后，为了不让权限丢失，都会进行权限维持，而在进行权限维持的时候，红队需要花费大量的时候，来验证是否合适，因此在这款工具就诞生 HackerPermKeeper[黑客权限保持者]
| :lock:权限维持模块           | centos             | Ubuntu             | 推荐指数                                         | 备注                                                         | py2                | py3                |
| :--------------------------- | ------------------ | ------------------ | ------------------------------------------------ | ------------------------------------------------------------ | ------------------ | ------------------ |
| OpenSSH后门万能密码&记录密码 | :x:                | :heavy_check_mark: | :star:                                           | 此后门需要很老的内核版本，而且需要很多依赖环境               | :x:                | :heavy_check_mark: |
| PAM后门                      | :x:                | :x:                | :star:                                           | 此后门需要很老的内核版本，而且需要很多依赖环境               | :x:                | :x:                |
| SSH软链接                    | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:                                 | 容易被发现                                                   | :heavy_check_mark: | :heavy_check_mark: |
| ssh公私密钥                  | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:	:star:	:star:	:star:   | 发现程度很难，参考了挖矿病毒                                 | :heavy_check_mark: | :heavy_check_mark: |
| 后门帐号                     | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:	:star:                       | 用命令添加账户，不会创建用户home目录[有一个是直接指向root目录] | :heavy_check_mark: | :heavy_check_mark: |
| crontab计划任务              | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:	:star:	:star:             | 难以发现，通过执行计划任务                                   | :heavy_check_mark: | :heavy_check_mark: |
| Strace后门                   | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:                                 | 键盘记录的后门                                               | :heavy_check_mark: | :heavy_check_mark: |
| Alias后门                    | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:	:star:	:star:             | 别名后门，难以发现，但是需要用户去执行命令                   | :heavy_check_mark: | :heavy_check_mark: |
| Rootkit后门[检测]            | :x:                | :x:                | :star:	:star:	:star:                       | 难以发现，但是安装复杂，而且指定内核版本                     | :x:                | :x:                |
| check.py                     | :heavy_check_mark: | :heavy_check_mark: | :star:	:star:	:star:	:star::star::star: | 快速检测目标机器可以使用那个权限维持模块                     | :heavy_check_mark: | :heavy_check_mark: |

### 项目亮点

快速进行检测linux适合那个权限维持模块，快速的进行linux权限维持。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
