### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by libaibaia** [knownsec/404StarLink#123]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

cloudSec-tool

### 项目地址

https://github.com/libaibaia/cloudSec

### 项目简介

测试中经常会遇到各家云厂商ak/sk泄露，由于每个厂商接口不统一，利用起来很繁琐，为了简化这类操作，衍生出了ak/sk利用平台，更方便利用各厂商云上资源进一步渗透。
- 功能概述
<table>
  <tr>
    <th>厂商</th>
    <th>产品</th>
    <th>功能</th>
    <th>备注</th>
  </tr>
  
  <tr>
    <td rowspan="4">七牛云</td>
    <td>云服务器</td>
    <td>列出云服务器/绑定密钥对</td>
    <td>/</td>
  </tr>
  
  <tr>
    <td>云数据库</td>
    <td>/</td>
    <td>/</td>
  </tr>
  
  <tr>
    <td>存储桶</td>
    <td>列出文件/单文件下载链接生成/上传文件/导出存储桶所有文件列表</td>
    <td>因为下载文件过多收费问题，所以改成了导出所有文件列表，然后通过文件名自己筛选即可，界面支持前缀搜索，支持1000条数据实时预览</td>
  </tr>
  
  <tr>
    <td>控制台用户</td>
    <td>/</td>
    <td>/</td>
  </tr>
   <tr>
    <td rowspan="4">华为云</td>
    <td>列出云服务器</td>
    <td>列出云服务器/绑定密钥对</td>
    <td>密钥对操作需要重启服务器</td>
  </tr>
  
  <tr>
    <td>云数据库</td>
    <td>获取数据库资源/创建用户</td>
    <td>不支持开通关闭外网访问，华为云数据库需要单独购买IP</td>
  </tr>
  
  <tr>
    <td>存储桶</td>
    <td>列出文件/单文件下载链接生成/上传文件/导出存储桶所有文件列表</td>
    <td>因为下载文件过多收费问题，所以改成了导出所有文件列表，然后通过文件名自己筛选即可，界面支持前缀搜索，支持1000条数据实时预览</td>
  </tr>
  
  <tr>
    <td>控制台用户</td>
    <td>创建控制台用户</td>
    <td>默认继承父账号权限</td>
  </tr>
  
  <tr>
    <td rowspan="4">阿里云</td>
    <td>云服务器</td>
    <td>列出云服务器/执行命令/绑定(还原)密钥对</td>
    <td>密钥对操作需要重启服务器</td>
  </tr>
  
  <tr>
    <td>云数据库</td>
    <td>获取数据库资源/创建用户/开通或关闭外网访问</td>
    <td>账号继承父账号权限</td>
  </tr>
  
  <tr>
    <td>存储桶</td>
    <td>列出文件/单文件下载链接生成/上传文件/导出存储桶所有文件列表</td>
    <td>因为下载文件过多收费问题，所以改成了导出所有文件列表，然后通过文件名自己筛选即可，界面支持前缀搜索，支持1000条数据实时预览</td>
  </tr>
  
  <tr>
    <td>控制台用户</td>
    <td>创建控制台用户</td>
    <td>默认管理员权限</td>
  </tr>
  
  <tr>
    <td rowspan="4">腾讯云</td>
    <td>云服务器</td>
    <td>列出云服务器/执行命令/绑定(还原)密钥对</td>
    <td>密钥对操作需要重启服务器</td>
  </tr>
  
  <tr>
    <td>云数据库</td>
    <td>获取数据库资源/创建用户/开通或关闭外网访问</td>
    <td>账号继承父账号权限</td>
  </tr>
  
  <tr>
    <td>存储桶</td>
    <td>列出文件/单文件下载链接生成/上传文件/导出存储桶所有文件列表</td>
    <td>因为下载文件过多收费问题，所以改成了导出所有文件列表，然后通过文件名自己筛选即可，界面支持前缀搜索，支持1000条数据实时预览</td>
  </tr>
  
  <tr>
    <td>控制台用户</td>
    <td>创建控制台用户</td>
    <td>默认父账号权限</td>
  </tr>
  
  <tr>
    <td rowspan="4">亚马逊云</td>
    <td>云服务器</td>
    <td>列出云服务器</td>
    <td>/</td>
  </tr>
  
  <tr>
    <td>云数据库</td>
    <td>列出数据库资源</td>
    <td>/</td>
  </tr>
  
  <tr>
    <td>存储桶</td>
    <td>列出文件/单文件下载链接生成/上传文件/导出存储桶所有文件列表</td>
    <td>因为下载文件过多收费问题，所以改成了导出所有文件列表，然后通过文件名自己筛选即可，界面支持前缀搜索，支持1000条数据实时预览</td>
  </tr>
  
  <tr>
    <td>控制台用户</td>
    <td>创建控制台用户</td>
    <td>默认最高权限</td>
  </tr>
</table>

### 项目亮点

- 便于管理：可同时存放扫描多个AK/SK，并展示进度，方便每个KEY管理及利用。
- 易用性：web界面操作，多人同步，添加AK/SK后自动检测。
- 目前项目持续更新中，后续打算加入云原生内容，如各厂商的K8S。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
