### ISSUE TITLE
[项目申请]:  js cookie逆向利器：js cookie变动监控可视化工具 & js cookie hook打条件断点

### ISSUE THREAD

**Issue by CC11001100** [knownsec/404StarLink#124]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Cookie Monitor Debugger Hook

### 项目地址

https://github.com/JSREI/js-cookie-monitor-debugger-hook

### 项目简介

属于Web安全的JavaScript加密逆向领域的辅助脚本工具，用于高效率的对Cookie类型的加密进行逆向分析。

### 项目亮点

- 条件断点：能够根据Cookie的增删改查等行为以及Cookie的Name/Value等打条件断点，进行外科手术式的精准hook，这是目前其他同类工具都无法做到的
- Cookie可视化：Cookie变化可视化，更高效率的观察Cookie加密的规律及流程 
![image](https://github.com/knownsec/404StarLink/assets/12819457/0299581e-fb0c-43eb-a38e-1449b39acb99)

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。

**Comment by CC11001100** [comment]
> 项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。

感谢老哥，已添加运营微信推进中 :smile:
