### ISSUE TITLE
[项目申请]: searchall敏感信息搜索工具

### ISSUE THREAD

**Issue by Naturehi666** [knownsec/404StarLink#125]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

searchall

### 项目地址

https://github.com/Naturehi666/searchall

### 项目简介

searchall可以快速搜索服务器中的有关username，passsword,账号，口令的敏感信息和常见的各种key和浏览器存储的敏感信息例如账号密码，历史记录，下载记录等。

### 项目亮点

1.它现在所具备的功能自动扫描以下所有文件类型

"text":     ".txt,.md,.conf,.json,",
"config":   ".cfg,.conf,.ini,.properties,.config,.xml,.env,",
"database": ".sql,.yaml,.yml,",
2.解决因线程过多导致目录扫不全问题 

3.增加/var/log/secure 扫描时取出登陆成功记录 

3.增加accessKeyId,accessKeySecret,jdbc匹配规则 

4.增加浏览器生成的result文件夹打包功能 

5.增加扫描有效文件数实时响应功能 

6.增加扫描服务器中是否安装docker功能

7.增加CorpId,CorpSecret,qq.im.sdkappid,qq.im.privateKey,qq.im.identifier的匹配规则

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！

**Comment by LoRexxar** [comment]
想法挺有意思的，写的有点儿简单了，如果轻量化慢扫描定位会更有用

**Comment by Naturehi666** [comment]
能不能深度交流一下呢&nbsp; ，不太懂 轻量化慢扫描定位 什么意思
&nbsp;


www.1050631369
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 上午9:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [knownsec/404StarLink] [项目申请]: searchall敏感信息搜索工具 (Issue #125)





 
想法挺有意思的，写的有点儿简单了，如果轻量化慢扫描定位会更有用

**Comment by LoRexxar** [comment]
说白了就是，你想没想过这个东西能用在啥地方啊。
总不可能是在自己的机器上用吧

**Comment by Naturehi666** [comment]
也没啊 我想用在内网机器上 这样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月21日(周一) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [knownsec/404StarLink] [项目申请]: searchall敏感信息搜索工具 (Issue #125)




 
说白了就是，你想没想过这个东西能用在啥地方啊。
 总不可能是在自己的机器上用吧

**Comment by LoRexxar** [comment]
对呀，那实际应用场景里要考虑的东西就多了呀，插件化，轻量化这些都要考虑

**Comment by Naturehi666** [comment]
他扫描内网机器的时候内存占用并不大，然后7m多应该也不算大把



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月21日(周一) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [knownsec/404StarLink] [项目申请]: searchall敏感信息搜索工具 (Issue #125)




 
对呀，那实际应用场景里要考虑的东西就多了呀，插件化，轻量化这些都要考虑

**Comment by Naturehi666** [comment]
插件化的意思 是不是写一个类似于 cs的插件那种



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月21日(周一) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [knownsec/404StarLink] [项目申请]: searchall敏感信息搜索工具 (Issue #125)




 
对呀，那实际应用场景里要考虑的东西就多了呀，插件化，轻量化这些都要考虑

**Comment by LoRexxar** [comment]
所以我说你写的时候没考虑太具体的场景，比如说有一个场景可以执行但是不能传参，或者有一个场景限制大小只能传几百k，或者只想搜一些特定的信息

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
