### ISSUE TITLE
[项目申请]: qsnctf-python

### ISSUE THREAD

**Issue by Moxin1044** [knownsec/404StarLink#128]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

qsnctf-python

### 项目地址

https://github.com/Moxin1044/qsnctf-python

### 项目简介

qsnctf-python是青少年CTF训练平台进行编写的一个Python包程序，意图在Python中为大家快速使用一些CTF常用功能开发的开源包。目前支持多种编解码方式，同时支持CTF中Web种爆破、扫描、写shell等多种操作。这里有很多CTF常用功能，如Base编码、hash加密，甚至少见的社会主义核心价值观编码、quipqiup等都在其中。

### 项目亮点

使用Python编写，集成为Python库，可以很方便的通过pip进行安装和调用。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
