### ISSUE TITLE
[项目申请]: Pscan

### ISSUE THREAD

**Issue by Moxin1044** [knownsec/404StarLink#129]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Pscan

### 项目地址

https://github.com/Moxin1044/Pscan

### 项目简介

Pscan是一个支持通过IP列表快速进行特定端口扫描的工具，支持自定义线程，并且支持导出相关列表。使用Golang编写，支持环境广泛，目前支持MacOS ARM64、AMD64、Linux大部分架构、Windows的大部分架构（如ARM、ARM64、i386、AMD64）。

较为适合在AWD比赛中批量扫描特定网段主机存活、端口开放，批量利用。

### 项目亮点

使用Golang编写，速度较快，支持多线程并发扫描，实测速度超越了Nmap加上-T4参数。支持系统广泛，支持ARM架构的机器。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
