### ISSUE TITLE
[项目申请]: AppScan申请

### ISSUE THREAD

**Issue by ChnMig** [knownsec/404StarLink#131]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

AppScan

### 项目地址

https://github.com/TongchengOpenSource/AppScan

### 项目简介

 它是一款基于动态分析, 可以 精准定位 APP 的违规风险点的自动化隐私检测工具, 能够大大 提高了合规检测的效率, 帮助使用者便捷、高效、全面的完成 合规检测, 保障业务合规运行.

### 项目亮点

全面性:  从信息收集、权限申请及数据传输等多个维度，实现对APP个人信息合规的全面检测。
规范性:  全面覆盖《App违法违规收集使用个人信息行为认定方法》、国家标准GB/T35273《信息安全技术 个人信息安全规范》、《中华人民共和国网络安全法》等主流安全检测标准。
高效性:  可帮助APP开发公司及开发者快速对APP进行日常合规检测，深度挖掘隐私合规风险点、快速处理大批量App，替代人工翻查代码，降低时间与人力成本，显著提升检测效率。
易用性:  无需环境搭配、开箱即用。

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
