### ISSUE TITLE
[项目申请]: Pillager

### ISSUE THREAD

**Issue by qwqdanchun** [knownsec/404StarLink#132]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Pillager

### 项目地址

https://github.com/qwqdanchun/Pillager

### 项目简介

这是一个敏感信息提取工具，目前支持大部分常见浏览器、若干聊天软件及部分其他软件信息的提取

### 项目亮点

目标是做一个红队渗透过程中可以一键收集信息的工具，还在陆续添加支持的软件
已添加部分均经过充分测试，确保了高可用性
为方便使用，项目提供了对应的CobaltStrike插件

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
