### ISSUE TITLE
[项目申请]: Choccy

### ISSUE THREAD

**Issue by l3yx** [knownsec/404StarLink#134]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Choccy

### 项目地址

https://github.com/l3yx/Choccy

### 项目简介

在分析开源项目的漏洞时，可能会总结一下针对于该项目的source点或者一些通用的sink点，编写针对性的CodeQL规则，然后尝试去发现更多开源项目类似的问题或者对原项目进行持续的监控。如果用Python脚本进行批量的扫描，手动的命令行操作不仅繁琐，而且纯文本的输出结果可读性很差，还是需要导入数据库到vscode的CodeQL插件中再次扫描。所以诞生了这款Web架构的图形化的 GitHub项目监控 && CodeQL自动扫描 工具，支持官方规则和自定义规则，对项目进行持续监控扫描，也完美复刻了vscode插件对一个漏洞详细的数据流路径的展示。

### 项目亮点

* GitHub项目监控与自动化扫描
* 支持官方规则与自定义规则的自由配置
* 图形化CodeQL

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
