### ISSUE TITLE
[项目申请]: pathScan

### ISSUE THREAD

**Issue by wjlin0** [knownsec/404StarLink#135]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

pathScan

### 项目地址

https://github.com/wjlin0/pathScan

### 项目简介

pathScan 是一个用Go编写的路径扫描、信息收集、端口扫描、指纹探索工具，它允许您快速可靠的扫描URL地址。这是一个非常简单的工具。

### 项目亮点

1. 快速递归扫描路径
2. 可实现yaml自定义指纹库
3. 端口扫描支持SYN快速扫描
4. 集成主流网络空间搜索引擎API 11+

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
