### ISSUE TITLE
[项目申请]: mostart

### ISSUE THREAD

**Issue by modstart** [knownsec/404StarLink#137]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

ModStartCMS

### 项目地址

https://github.com/modstart/ModStartCMS

### 项目简介

ModStart 是一个基于 Laravel 的模块化快速开发框架。模块市场拥有丰富的功能应用，支持后台一键快速安装，让开发者能快的实现业务功能开发。

### 项目亮点

一个Laravel模块化开发框架 ModStart，支持超多成熟模块

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
