### ISSUE TITLE
[项目申请]: 昆吾webshell检测

### ISSUE THREAD

**Issue by ctccaozhe** [knownsec/404StarLink#140]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

昆吾webshell检测

### 项目地址

https://github.com/kunwu2023/kunwu

### 项目简介

- KunWu 是一款webshell检测工具，有云端检测引擎和离线检测引擎。
- KunWu 全平台支持。支持cli、gui、在线使用等多种使用场景。
- KunWu 支持快速扫描、本地扫描、远程扫描；上传或拖拽文件开始扫描！
> 在线版地址：[点击访问](https://ti.moresec.cn/) 

### 项目亮点

fas4w3t3w4t45w3ete45y4e56ye56
90-9-
8-
88-
90
880
90

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！

**Comment by ctccaozhe** [comment]
误点发送，等完善内容后重新提交
