### ISSUE TITLE
[项目申请]: CaA项目

### ISSUE THREAD

**Issue by gh0stkey** [knownsec/404StarLink#143]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

CaA

### 项目地址

https://github.com/gh0stkey/CaA

### 项目简介

CaA是一个基于BurpSuite Java插件API开发的流量收集和分析插件。它的主要作用就是收集HTTP协议报文中的参数、路径、文件、参数值等信息，并统计出现的频次，为使用者积累真正具有实战意义的Fuzzing字典。除此之外，CaA还提供了独立的Fuzzing功能，可以根据用户输入的字典，以不同的请求方式交叉遍历请求，从而帮助用户发现隐藏的参数、路径、文件，以便于进一步发现安全漏洞。

### 项目亮点

1. 填补国内外Web Fuzzing辅助型工具的空缺；
2. 具备实战化的设计，如统计出现频次可以更好的筛选出有意义的字典，以及自带的Fuzzing模块可以完成基础性的Web Fuzzing工作；
3. 与星链项目`HaE`，具有联动意义，当HaE发现一条具有敏感数据返回的API信息，就可以基于CaA一键扫描，探寻出隐藏的参数、路径、文件等信息。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！
