### ISSUE TITLE
[项目申请]: LC

### ISSUE THREAD

**Issue by teamssix** [knownsec/404StarLink#145]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

LC

### 项目地址

https://github.com/wgpsec/lc

### 项目简介

LC（List Cloud）是一个多云攻击面资产梳理的工具，使用 LC 可以让甲方蓝队在管理多云时快速梳理出可能暴露在公网上的资产。

### 项目亮点

企业在做安全建设时，很重要的一步就是要梳理出自己的攻击面，随着企业不断地上云，云上攻击面的梳理变成了一个新的课题。
在云环境中，如果企业只使用一个云那么直接使用云厂商官方工具就能够很好的管理资产，但现实是大部分企业因为考虑到业务稳定等因素，几乎都会选择多云，这时就造成了多云资产管理的困难。这个困难无法指望云厂商去解决，只能由第三方去解决，而 LC 在一定程度上缓解了这个问题，下面是 LC 的一些亮点。

1. 支持同时列出多云中的多个服务的资产，一键列出企业的多云资产，帮助甲方快速找到存在风险的云上资产
2. 除了支持阿里、腾讯、华为三大云之外，还对天翼、联通、移动等云厂商进行了支持
3. 支持使用管道符和其他命令相结合使用，具有较高的扩展性与使用空间

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
