### ISSUE TITLE
[项目申请]: Pilot漏洞测试教学靶场

### ISSUE THREAD

**Issue by 2740908911** [knownsec/404StarLink#147]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Pilot-Web

### 项目地址

https://github.com/2740908911/Pilot-Web

### 项目简介

Pilot领航员靶场是基于Web安全的漏洞测试靶场，一个专为教师和学生设计的WEB安全教学实践平台，旨在帮助网安初学者快速熟悉和掌握目前常见漏洞的原理和实际利用方法，以及帮助安全实践教师在课堂环境中演示教学如何进行WEB漏洞测试。
Pilot靶场由 Flask + Mysql + AdminLTE 框架编写而成，靶场模拟出15大类漏洞细分的30个漏洞环境，通过思路提示、正确实现、源码解析、知识梳理和靶场文档等功能提供学习辅助。
Pilot靶场整体通过Docker封装打包，使用Docker-Compose进行容器管理，并设计了快速部署脚本以便用来配置分发和快速部署服务。

### 项目亮点

1. 少数Python环境的开源WEB漏洞靶场。
2. 唯一集成知识库、漏洞学习文档和源码解析等功能的开源综合型教学靶场。
3. 对比同类产品更全面的漏洞类型。
4. 更简单的部署方式和更方便的配置管理方式。
5. 全新的UI设计，更近现代靶场设计。
6. 更简单的配置管理和部署方案。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，期待项目后续更新和随时欢迎再次投稿，谢谢！
