### ISSUE TITLE
[项目申请]: fofa_viewer

### ISSUE THREAD

**Issue by keac** [knownsec/404StarLink#148]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

fofa_viewer

### 项目地址

https://github.com/wgpsec/fofa_viewer

### 项目简介

Fofa Viewer 是一个用 JavaFX 编写的用户友好的 FOFA 客户端，属于 WgpSec 社区，主要由 f1ashine 维护。 利用强大的互联网搜索引擎FoFa，将众多常用的API封装到简洁的UI中，让网络安全专业人士更容易在目标网站上寻找漏洞。 凭借其开箱即用的功能，Fofa Viewer 简化了搜索过程，帮助渗透测试人员快速获取所需信息。

### 项目亮点

1. 多标签式查询结果展示
2. 丰富的右键菜单
3. 支持查询结果导出为excel文件
4. 支持手动修改查询最大条数，方便非高级会员使用(修改config.properties中的maxSize即可)
5. 支持证书转换 将证书序列填写入启动页框内可转换，再使用 cert="计算出来的值" 语法进行查询
6. 支持输入智能提示
7. 支持fofa的一键排除干扰（蜜罐）功能。（注：需要高级会员，使用时会在tab页标记(*)）
8. 支持Fid查询（注：需要高级会员，查询时需要勾选）
9. 支持full查询(查询全部数据)

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，期待项目后续更新和随时欢迎再次投稿，谢谢！

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，谢谢！
