### ISSUE TITLE
[项目申请]: EndpointSearch

### ISSUE THREAD

**Issue by shadowabi** [knownsec/404StarLink#149]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

EndpointSearch

### 项目地址

https://github.com/wgpsec/EndpointSearch

### 项目简介

EndpointSearch 是一个探测云服务端点的扫描器。

### 项目亮点

1. DNS枚举:根据预定义的模式为可能的云服务端点url构造和查询DNS。
2. SRV记录检测:自动检测SRV记录，发现关联端口。
3. HTTP/HTTPS探测:当SRV记录不存在时，使用HTTP和HTTPS协议测试端点。
4. 云服务端点判断:根据响应内容确定端点的可能性。
5. 自动域名提取:自动从输入的url中提取域名。
6. 输出冗余去除:通过重复数据删除确保输出结果唯一。
7. 可配置行为:提供灵活的配置文件，用于自定义服务名称、连接模式等。

使用场景：
1. 非公有云环境下的云服务端点侦查，以获取云服务横向的机会
2. 公有云环境下侦查非生产云服务端点，以绕过云监控，具体参考BLACK HAT 2023议题：Evading Logging in the Cloud: Bypassing AWS CloudTrail

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，期待项目后续更新和随时欢迎再次投稿，谢谢！
