### ISSUE TITLE
[项目申请]: WIHscan

### ISSUE THREAD

**Issue by ifacker** [knownsec/404StarLink#150]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

WIHscan

### 项目地址

https://github.com/ifacker/WIHscan

### 项目简介

WIHscan 主要是灯塔 WIH 模块的利用，通过获取扫描的存在敏感信息的 js 进行信息提取，也可以对指定的一些 js 进行敏感信息扫描，包括一些 AK/SK 之类的，可以去 config/ 中自定义规则，从而匹配出自己想要的结果（需要会点正则表达式）

### 项目亮点

目前没见到开源的 WIH 利用，所以写了一个，方便利用。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，期待项目后续更新和随时欢迎再次投稿，谢谢！
