### ISSUE TITLE
[项目申请]: Galaxy

### ISSUE THREAD

**Issue by outlaws-bai** [knownsec/404StarLink#151]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Galaxy

### 项目地址

https://github.com/outlaws-bai/Galaxy

### 项目简介

越来越多的网站对HTTP流量做了二次加密，在理清加密逻辑后，如何对明文流量高效的进行渗透测试是一个问题。
Galaxy很好的解决了这个问题，它是一款Burp Suite插件，允许用户在Request/Response在Client/Burp/Server流转时实现自己的处理逻辑，并支持多种实现方式，Python、JS、Grpc...

业内有类似方案或工具，但各有缺点，或使用麻烦不够高效、或无法支持复杂的加密场景(算法组合、动态密钥)、或需要启动本地服务等等。 Galaxy吸收了这些工具的优点，极大的简化了使用，并支持各种复杂的加密场景。

### 项目亮点

简单高效：用户不需要启动多余的本地服务，配置成功后可以自动对报文进行加解密。
上手容易：通用算法已有示例，能做到开箱即用。
强灵活性：可以使用Python、JS、Java、Grpc多种方式实现自己的处理逻辑。
支持面广：如加密算法组合、自定义算法、动态密钥等均可以支持。

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404链计划技术评审阶段，后续项目期待更新并欢迎再次投稿，谢谢！
