### ISSUE TITLE
[项目申请]: GrabAccess

### ISSUE THREAD

**Issue by Push3AX** [knownsec/404StarLink#152]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

GrabAccess

### 项目地址

https://github.com/Push3AX/GrabAccess

### 项目简介

**GrabAccess：Bookit / Windows登陆密码和Bitlocker绕过工具**
在物理接触目标计算机的情况下，GrabAccess可以：
1. 绕过Windows登陆密码执行任意操作（以System权限执行命令、重置Windows账户密码等）
2. 植入木马并添加自启动（可以绕过Bitlocker，但要求受害者登录）
3. 通过修改主板UEFI固件实现无视重装系统、更换硬盘的持久化（Bootkit）

### 项目亮点

1、可用于绕过Windows登陆密码或植入主板级Bootkit后门。
2、（可能是）目前唯一开源的windows登陆密码绕过工具。
3、目前最易于配置的Windows Bootkit。
4、基于Windows合法机制实现，稳定通杀主流windows（UEFI环境下）。

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
