### ISSUE TITLE
[项目申请]: e0e1-wx

### ISSUE THREAD

**Issue by eeeeeeeeee-code** [knownsec/404StarLink#154]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

e0e1-wx

### 项目地址

https://github.com/eeeeeeeeee-code/e0e1-wx

### 项目简介

立志自动化辅助小程序渗透，主要功能有自动化辅助反编译、自动化注入hook、自动化查看泄露、自动化提取接口或url等，精准辅助fuzz，同时自动化hook辅助进阶渗透，省去了多方面重复浪费时间的操作。

### 项目亮点

1.自动化反编译
2.自动化hook小程序F12
3.自动化提取敏感信息、接口、url等

**Comment by Knownsec404team** [comment]
您好，感谢投稿。很遗憾项目未通过404星链计划技术评审阶段，期待项目后续的更新和迭代，欢迎再次投稿，谢谢！
