### ISSUE TITLE
[项目申请]: FastSee

### ISSUE THREAD

**Issue by s-kyx** [knownsec/404StarLink#155]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

更快更好用的url存活探测工具—FastSee

### 项目地址

https://gitee.com/ma-fanxiang/fast-see

### 项目简介

python极速url探测工具，支持多请求方式的异步协程存活探测、协程异步的批量截屏探测，生成清晰的结果存储和html报告，通过异步生成器加载和写入文件，优化了探测速度

### 项目亮点

1.又快又准：在保证探测准确率的基础上加快探测速度，采用异步生成器加载文件的同时采取了协程高并发对url进行探测

2.人性化功能：url自动去重，无协议的url自动进行http和https双协议探测，在双协议探测后支持对存活的url的协议合并去重，支持更改存活探测的请求方法：get/post/put

3.可自定义性强：可自定义探测请求并发数、请求头、文件保存名等。

4.便捷生成文件：txt只保存url结果，且将状态码为200的url自动单独保存为一个txt文件，excel存储url、状态码、标题,分两张工作表存储，其中一张工作表只存放状态码为200的数据。

5直观报告：截屏探测 的html报告的url支持一键点击转跳、图片也可点击查看大图；存活探测生成 的excel的url也支持直接的点击转跳到浏览器直接打开

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by s-kyx** [comment]
嗯呢，希望可以通过，很热爱工具开发，最近又更新了很多新功能，对标的是httpx，比他要更快更方便

**Comment by s-kyx** [comment]
您好，最近又更新啦，项目一直积极维护

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！
