### ISSUE TITLE
[项目申请]: go-portScan

### ISSUE THREAD

**Issue by XinRoom** [knownsec/404StarLink#157]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

go-portScan

### 项目地址

https://github.com/XinRoom/go-portScan

### 项目简介

go语言开发的高性能端口扫描器，支持syn无状态端口扫描，支持ipv6的syn无状态端口扫描。支持端口指纹识别、web指纹识别。

### 项目亮点

- SYN无状态/TCP扫描
- IPV6 SYN支持
- 大地址段/IPV6地址段扫描支持
- 端口指纹识别
- WEB指纹识别
- 可以作为依赖库使用

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！

**Comment by lanyi1998** [comment]
Good Job

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！
