### ISSUE TITLE
[项目申请]: AutorizePro

### ISSUE THREAD

**Issue by sule01u** [knownsec/404StarLink#158]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

AutorizePro

### 项目地址

https://github.com/sule01u/AutorizePro

### 项目简介

AutorizePro 是一款专注于越权检测的 Burp 插件，增加了 **AI分析** 模块 && 优化检测逻辑，启用AI分析功能后可大幅降低越权工具普遍存在的误报率高的问题，同等测试条件下需要分析的误报率可从 99% 下降至 5%，提高安全人员发现越权漏洞的效率。

### 项目亮点

AI分析功能可大幅降低了越权工具普遍存在的误报率高的问题，同等测试条件下需要分析的告警数量下降95%，提高安全人员发现越权漏洞的效率。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
