### ISSUE TITLE
[项目申请]: Xtate

### ISSUE THREAD

**Issue by sharkocha** [knownsec/404StarLink#159]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Xtate

### 项目地址

https://github.com/sharkocha/xtate

### 项目简介

Xtate是面向互联网规模网络测量的模块化全栈扫描器（框架）。利用自研的应用层无状态扫描模型ZBanner和混合状态轻量级TCP协议栈HLTCP实现异步高速扫描。

与已有的无状态端口扫描器只能探测端口是否开放不同，Xtate基于应用层无状态扫描模型，在千兆带宽下能够在6分钟内完成中国大陆地址集中所有80端口的开放性检测和Banner抓取。基于HLTCP用户态协议栈实现和TLS支持，Xtate也能够在有状态模式下执行多轮数据交互的高速扫描，包括TLS上层服务Banner抓取。

Xtate框架提供统一接口以自定义模块实现不同的扫描任务，专注于大规模网络的协议层面测量（包括传输层、应用层和TLS上层服务），具有坚实的底层高速异步数据包收发机制，期望为学术和实践领域中大规模网络测量的各种算法和任务提供承载平台。

需要说明的是，Xtate可以做到、但不适用于应用层内容获取类型的任务（漏扫、爬虫等），该领域已有其它成熟工具。
现已实现11种扫描模块、59种探针模块等，包含常用功能：端口扫描、服务发现、Banner抓取、路径探测等。

由于是硕士期间研究内容的配套实现，兼具学术研究和工程性质，可配置参数和各模块子参数较多，但所有参数说明都有对应帮助和说明，且均已嵌入程序，可通过命令查看。具体使用过程中，可能还需要用户具有相应的计算机网络和涉及的网络测量任务相关背景知识。

### 项目亮点

- 专为学术和实践领域中的互联网规模网络测量而设计的框架，可作为承载各类扫描任务和探测策略、算法等的平台；
- 具备自研的应用层无状态扫描模型（ZBanner）和混合状态轻量级TCP协议栈（HLTCP）；
- 提供大规模测量需要的基础设置，包括高速数据包收发机制、地址随机化、结果去重等；
- 抽象探测过程为模块，提供编写接口，实现自定义探测任务、策略等，其中扫描模块和探针模块可选择适用lua脚本编写；
- 已实现常用功能的模块实现作为示例，包括端口扫描、服务发现、Banner抓取、路径探测等。
- C语言编写，使用CMake构建，可跨平台编译（Windows/Linux），大部分依赖库可选编译，不影响主体功能。

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
