### ISSUE TITLE
[项目申请]: dirmap

### ISSUE THREAD

**Issue by H4ckForJob** [knownsec/404StarLink#160]
### 基本要求

- [x] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

dirmap

### 项目地址

https://github.com/H4ckForJob/dirmap/

### 项目简介

An advanced web directory & file scanning tool that will be more powerful than DirBuster, Dirsearch, cansina, and Yu Jian.一个高级web目录、文件扫描工具，功能将会强于DirBuster、Dirsearch、cansina、御剑。

### 项目亮点

1. 支持n个target\*n个payload并发
2. 支持递归扫描
3. 支持自定义需要递归扫描的状态码
4. 支持(单|多)字典扫描
5. 支持自定义字符集爆破
6. 支持爬虫动态字典扫描
7. 支持自定义标签fuzz目标url
8. 自定义请求User-Agent
9. 自定义请求随机延时
10. 自定义请求超时时间
11. 自定义请求代理
12. 自定义正则表达式匹配假性404页面
13. 自定义要处理的响应状态码
14. 自定义跳过大小为x的页面
15. 自定义显示content-type
16. 自定义显示页面大小
17. 按域名去重复保存结果

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
