### ISSUE TITLE
MySQL_Fake_Server

### ISSUE THREAD

**Issue by fnmsd** [knownsec/404StarLink#29]
### 项目名称

MySQL_Fake_Server

### 项目链接

https://github.com/fnmsd/MySQL_Fake_Server

### 项目简介

用于渗透测试过程中的假MySQL服务器，纯原生python3实现，不依赖其它包。

### 项目特点、亮点

1. 纯原生Python实现，无其它依赖包，有Python3就能用。
2. 支持目前所有场景下的MySQL JDBC Connector反序列化利用。
3. 支持MySQL客户端大文件的完整读取（包括二进制文件）。
4. 最新版本增加了未知用户名登录时，随机读取预置的文件路径，可以当做蜜罐使用。

**Comment by 0x7Fancy** [comment]
项目很赞哦，请添加下 README 末尾的运营微信账号，便于沟通以及推进项目加入流程。(同时，请熟悉下项目加入流程 https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join，稍微完善下项目规范，便于用户使用以及我们后续的项目动态跟踪)

**Comment by 0x7Fancy** [comment]
项目很赞哦，请添加下 README 末尾的运营微信账号，便于沟通以及推进项目加入流程。(同时，请熟悉下项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)，稍微完善下项目规范，便于用户使用以及我们后续的项目动态跟踪)
