### ISSUE TITLE
RabR

### ISSUE THREAD

**Issue by 0671** [knownsec/404StarLink#31]
### RabR

Redis-Attack By Replication (通过主从复制攻击Redis)

### 项目链接

https://github.com/0671/RabR

### 项目简介

利用Redis的主从复制功能（>=2.8）、模块功能（>=4）、dll劫持，对Linux下的Redis进行攻击，可执行命令和反弹shell，对Window x64下的Redis攻击，可执行命令。

### 项目特点、亮点
1. 本工具可以对Windows、Linux下的Redis进行攻击。
1. github上**第一个针对Windows下的Redis进行模块攻击**的工具（module load可执行系统命令的模块）。
2. 主从复制中会清空从机（目标Redis）的数据，本工具在**一定程度上可以保护目标Redis的数据**，即在攻击中，会恢复目标Redis的数据。
3. 工具自带**Redis爆破功能**。

**Comment by 0x7Fancy** [comment]
项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿
