### ISSUE TITLE
pwcrack-framework

### ISSUE THREAD

**Issue by L-codes** [knownsec/404StarLink#33]
### 项目名称

pwcrack-framework

### 项目链接

https://github.com/L-codes/pwcrack-framework

### 项目简介

自动破解常见的hash和加解密，目前支持48种算法破解如蓝凌、致远、帆软和navicat等

### 项目特点、亮点

1. 自动识别密文可能的算法，并响应的进行解密尝试
2. hash支持在线接口进行破解，目前有25个在线接口
3. 支持部分cmd5收费的密码生成的本地库减少收费查询
4. 优雅的DSL插件语法，方便添加新的算法破解插件

**Comment by 0x7Fancy** [comment]
项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿

**Comment by L-codes** [comment]
@0x7Fancy 同样的请问是否能给予回馈信息？mx1014的项目也是不鸟人了
