### ISSUE TITLE
BurpCrypto

### ISSUE THREAD

**Issue by whwlsfb** [knownsec/404StarLink#34]
### 项目名称
BurpCrypto

### 项目链接

https://github.com/whwlsfb/BurpCrypto

### 项目简介

支持多种加密算法或直接执行JS代码的用于爆破前端加密的BurpSuite插件。

### 项目特点、亮点

- 集成AES、DES、RSA和大部分对应的加密模式与填充算法。
- 支持多种密钥输入与密文输出格式（UTF8String、HEX、Base64）。
- 支持直接执行JS代码，在部分BurpSuite版本中支持语法高亮编辑器，支持多种JS执行引擎（Jre内置、HtmlUnit、Rhino，目前默认使用Rhino）。
- 内置密文/明文本地持久化KV数据库，通过该插件输出的密文内容可轻松查询出明文。

**Comment by 0x7Fancy** [comment]
项目很赞哦，请添加下 README 末尾的运营微信账号，便于沟通以及推进项目加入流程。(同时，请熟悉下项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)，稍微完善下项目规范，便于用户使用以及我们后续的项目动态跟踪)
