### ISSUE TITLE
scaninfo

### ISSUE THREAD

**Issue by simlelcf** [knownsec/404StarLink#41]
## 项目地址

https://github.com/redtoolskobe/scaninfo

## 项目亮点

- 快速的web重点指纹识别
- 更快的端口服务扫描(不限于端口，可以准确的识别常规的服务。且只用一次socket连接)
- 友好的报告输出
- golang跨平台
- 内外网打点
- 实时的进度条大批量扫的时候很实用

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下 README 末尾的运营微信账号，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
