### ISSUE TITLE
Kernelhub

### ISSUE THREAD

**Issue by Ascotbe** [knownsec/404StarLink#44]
### 项目名称

Kernelhub

### 项目链接

https://github.com/Ascotbe/Kernelhub

### 项目简介

本项目是一个提权相关的集合

### 项目特点、亮点

每个EXP都有详细说明、演示GIF图、相关分析文章，包括对应的测试机器版本和镜像，减少验证在网络上搜索和验证EXP的时间，减少学习相关漏洞的成本，实战中也可以快速利用获取高权限

后续将会更新Linux相关漏洞

**Comment by 0x7Fancy** [comment]
内容很赞，不过目前我们主要收录开源项目/工具这一块，分析文章欢迎投稿到 <https://paper.seebug.org>
