### ISSUE TITLE
chrome V8源码分析

### ISSUE THREAD

**Issue by v8blink** [knownsec/404StarLink#46]
### 项目名称   
chrome V8源码分析	
### 项目链接    
https://github.com/v8blink/v8-JavaScript-Documents  
### 项目简介  
本系列文章，讲解V8源码，力求做到全面覆盖知识点、有理论支撑，做到细致讲解源码、有实践依据。3~4天一篇，持续更新中...  
### 项目特点、亮点    
本系列文章，从基础入手，对V8内存分配、Isolate创建、handles概念、builtin、codegen、编译等每个方面进行详细讲解。

**Comment by 0x7Fancy** [comment]
文章内容很赞，不过我们目前仅收录开源项目哦

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！
