### ISSUE TITLE
BurpExtend

### ISSUE THREAD

**Issue by dongfangyuxiao** [knownsec/404StarLink#48]
项目名称：BurpExtend
项目链接：https://github.com/dongfangyuxiao/BurpExtend
项目简介：渗透测试自动化是白帽子和各家公司一直在解决的一个课题，BurpSuit是渗透测试中必不可少的渗透神器，基于BurpSuit插件二次开发，完善丰富其功能，联动各类其他工具达到渗透测试自动化能够有效减少人工的参与和大大提高漏洞检出率。
项目特点、亮点：自动化、多内容、更联动、有效性高

**Comment by 0x7Fancy** [comment]
项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿
