### ISSUE TITLE
Savior

### ISSUE THREAD

**Issue by Mustard404** [knownsec/404StarLink#49]
### 项目名称
Savior

### 项目链接
https://github.com/Mustard404/Savior

### 项目简介
渗透测试报告自动生成工具!

### 项目特点、亮点
做过安服的人都知道，输出的渗透测试报告经常出现结果不规范，在报告质量、内容、字体及修复方案中存在诸多问题。因此作者花费一年研发了Savior—渗透测试报告辅助生成系统，帮助渗透测试工程师告别繁琐的渗透测试报告编写过程及漏洞统计过程。主要功能：用户管理、项目管理、修复建议联动、漏洞跟踪、漏洞统计，并支持自定义模板。

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by 0x7Fancy** [comment]
项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿

**Comment by Mustard404** [comment]
项目内容不符合404星链计划要求，还是什么其它原因
