### ISSUE TITLE
Polaris

### ISSUE THREAD

**Issue by doimet** [knownsec/404StarLink#51]
### 项目名称
Polaris - 渗透测试框架

### 项目链接
https://github.com/doimet/Polaris

### 项目简介
这是一款集信息收集、漏洞利用、漏洞爆破等功能的一体化渗透测试框架

### 项目特点、亮点

+ 兼容XRay语法
+ 插件扩展性高
+ 模块自由组合
+ 插件支持异步
+ 界面美观舒适

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
