### ISSUE TITLE
xp_CAPTCHA

### ISSUE THREAD

**Issue by smxiazi** [knownsec/404StarLink#53]
项目名称
xp_CAPTCHA

项目链接
https://github.com/smxiazi/NEW_xp_CAPTCHA

项目简介
burp插件，主要用于登陆处的验证码识别。

项目特点、亮点
用于平时渗透测试过程中遇到验证码，可以用该插件对于验证码进行识别爆破。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
