### ISSUE TITLE
最好用的Acunetix AWVS扫描器开发的批量扫描脚本

### ISSUE THREAD

**Issue by test502git** [knownsec/404StarLink#56]
### 项目名称
	Acunetix AWVS扫描器开发的批量扫描脚本

### 项目链接
https://github.com/test502git/awvs14-scan

### 项目简介
针对 Acunetix AWVS扫描器开发的批量扫描脚本，支持log4j漏洞、SQL注入、XSS、弱口令等专项，支持联动xray、burp、w13scan等被动批量

### 项目特点、亮点
支持URL批量添加扫描
支持批量仅扫描apache-log4j漏洞
支持对批量url添加cooKie凭证进行爬虫扫描
支持对批量url添加1个或多个不同请求头
支持配置上级代理地址，能结合被动扫描器进行配置扫描,如：xray,w13scan,burp等扫描器
支持一键清空所有任务
通过配置config.ini文件，支持自定义各种扫描参数，如:爬虫速度，排除路径(不扫描的目录),全局cookie,限制为仅包含地址和子目录
支持对扫描器内已有目标进行批量扫描，支持自定义扫描类型

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
