### ISSUE TITLE
libphpserialize

### ISSUE THREAD

**Issue by frankli0324** [knownsec/404StarLink#63]
### 项目名称

libphpserialize

### 项目链接

https://github.com/frankli0324/libphpserialize

### 项目简介

php `serialize` 的纯python实现

Features

* 支持python对象的直接序列化
* 支持对象嵌套
* 支持对象引用
* namespace
* public, private, protected

### 项目特点、亮点

直观、高效地生成php序列化数据

https://blog.frankli.site/2021/06/15/Misc/libphpserialize/

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
