### ISSUE TITLE
odin project

### ISSUE THREAD

**Issue by PotatoCloud** [knownsec/404StarLink#65]
### 项目名称
Odin

### 项目链接
[https://github.com/Orl0g/Odin](https://github.com/Orl0g/Odin)

### 项目简介

Odin is an infinitely powerful red/blue team tool (weaponization), supports custom super-modules, the default modules {Eye/illusion/scepter} are respectively {Trojan/phishing/traffic hijacking, injection, tampering}, with In internal network security level testing and law enforcement investigation and evidence collection

### 项目特点、亮点

 - infinitely powerful
 - flexible deployment
 - advanced thinking
 - excellent degree of customization
 - GPLV3 license

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！
