### ISSUE TITLE
Ingram

### ISSUE THREAD

**Issue by jorhelp** [knownsec/404StarLink#66]
### 项目名称 && 项目链接

[Ingram](https://github.com/jorhelp/Ingram)

### 项目简介

一款专门针对网络摄像头是否存在漏洞的扫描工具，目前支持几款常见摄像头(海康、大华、汉邦等）的弱口令以及常见CVE

![](https://github.com/jorhelp/Ingram/blob/master/statics/imgs/run_time.png)

### 项目特点、亮点

一行命令即可完成部署，支持多线程快速扫描，实时显示扫描进度，完善的结果展示与记录。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
