### ISSUE TITLE
CF 云环境利用框架

### ISSUE THREAD

**Issue by teamssix** [knownsec/404StarLink#68]
### 项目名称
CF
### 项目链接
https://github.com/teamssix/cf
### 项目简介
CF 是一个云环境利用框架，主要用来方便红队人员在获得云服务 Access Key 的后续工作。
### 项目特点、亮点
* 当获取到 AK 的时候，一般最想知道的就是这个 AK 有什么权限、我能做什么，通过 CF 可以一键获取当前 AK 的权限，一下子就让蒙住的眼睛明亮了起来。
* 知道 AK 的权限后，最普遍的做法就是看看 OSS 上的文件，要不就是在 ECS 实例上执行个命令，但有了 CF 可以做更多，比如一键下载 OSS 所有资源、一键获取所有 ECS 实例上的临时访问凭证从而进行下一步的云上内网横向、一键为所有 ECS 实例执行三要素命令从而方便 HW。
* CF 它还能做更多，比如一键列出当前 AK 下的云服务资源（目前已支持 OSS、ECS、RDS）、一键创建后门管理员用户从而接管控制台、一键为 ECS 实例反弹 Shell 等等，使用 CF 可以让你的云上渗透效率提升到新的高度。

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
