### ISSUE TITLE
BucketScan存储桶扫描检测利用工具

### ISSUE THREAD

**Issue by UzJu** [knownsec/404StarLink#70]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Cloud-Bucket-Leak-Detection-Tools

### 项目地址

https://github.com/UzJu/Cloud-Bucket-Leak-Detection-Tools

### 项目简介

云原生安全近几年比较火，存储桶在企业(SRC众测)中暴露的问题也非常多，不仅仅局限于AK/SK的泄露，更多的是用户配置侧的问题，这款工具就是用来代替我们手工解决一些繁琐的操作。

### 项目亮点

- 该工具可以做什么？
 - 实现腾讯云，华为云，阿里云，AWS四个厂商的存储桶扫描利用功能
 - 1、自动检测存储桶的危险操作，例如PutObjet，GetBucketACL，PutBucketACL，DeleteObject等
 - 2、自动劫持存储桶，通过域名是否解析了CNAME和是否返回NoSuchBucket进行检测
 - 3、批量检测，可批量导入存储桶地址，域名自动化扫描并输出结果，该功能在fofa等平台上获取到的存储桶地址，大量扫描后发现大量的存储桶都存在不同的问题。

**Comment by UzJu** [comment]
update

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
