### ISSUE TITLE
Cola Dnslog 更加强大的dnslog平台

### ISSUE THREAD

**Issue by AbelChe** [knownsec/404StarLink#73]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [x] 6. 项目将会积极维护

### 项目名称

Cola Dnslog

### 项目地址

https://github.com/AbelChe/cola_dnslog

### 项目简介

1. Cola Dnslog 更加强大的dnslog平台/无回显漏洞探测辅助平台
2. 完全开源
3. dnslog httplog ldaplog rmilog
4. 提供API调用方式便于与其他工具结合
5. 集成钉钉机器人、Bark等提醒方式
6. 后端完全使用python实现
7. 前端基于vue-element-admin二开

### 项目亮点

除dns和http，还支持ldap、rmi协议log
支持持钉钉机器人、bark提醒
后端完全使用python
提供webui

**Comment by Knownsec404team** [comment]
项目很赞哦，404星链计划团队有一些建议已私下与您沟通！期待更新~

**Comment by AbelChe** [comment]
更新到1.3.0版本，添加了api说明文档，支持docker部署
