### ISSUE TITLE
Hades 跨端主机入侵检测系统

### ISSUE THREAD

**Issue by chriskaliX** [knownsec/404StarLink#76]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Hades

### 项目地址

https://github.com/theSecHunter/Hades

### 项目简介

Hades 是一款支持 windows/linux 的内核级主机入侵检测系统。Linux 部分基于 eBPF 以及 cn_proc，参考 Elkeid，tracee 开发；Windows 提供基于etw和内核两种采集模式，带有局部 edr 和行为检测。
Windows 部分由 @TimelifeCzy 负责开发
Linux 部分由 @chriskaliX 负责开发
目前除 Hboat(server) 外，其他均已较为成熟，能够单独运行

### 项目亮点

1. 稳定性：Windows 端多台无盘机器稳定运行测试；Linux 端基于 eBPF(低版本 netlink)，不会造成内核crash，已有人对eBPF部分进行二开并且企业内推广
2. 数据源丰富：两端都基于内核级别做数据采集，用户态做数据填充以及其余定时采集
3. 跨端：Hades 项目Win/Linux端分别维护，支持统一上报至 Server 端

项目目前持续开发中，主要由 @TimelifeCzy 、@chriskaliX 业余时间维护

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
