### ISSUE TITLE
[项目申请]: URLFinder

### ISSUE THREAD

**Issue by pingc0y** [knownsec/404StarLink#77]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

URLFinder

### 项目地址

https://github.com/pingc0y/URLFinder

### 项目简介

URLFinder是一款用于快速提取检测页面中JS与URL的工具。
通常用于快速查找隐藏在页面或js中的敏感及未授权api接口。

### 项目亮点

获取到的链接会返回状态码及响应大小
支持导出结果到csv文件
支持批量url
对抓取的链接做了划分，方便查找重点链接
支持多线程

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
