### ISSUE TITLE
[项目申请]: Antenna

### ISSUE THREAD

**Issue by bios000** [knownsec/404StarLink#78]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

Antenna

### 项目地址

https://github.com/wuba/Antenna

### 项目简介

Antenna是58同城安全团队打造的一款辅助安全从业人员辅助验证网络中多种漏洞是否存在以及可利用性的工具。其基于带外应用安全测试( OAST)通过任务的形式，将不同漏洞场景检测能力通过插件的形式进行集合，通过与目标进行Out-of-bind的数据通信方式进行辅助检测。

### 项目亮点

1、基础版支持HTTP/DNS/RMI/LADP等协议请求监听组件
2、支持XSS\XXE\JSONP\SSRF以及自定义http返回资源等漏洞场景利用组件
3、良好的用户体验，支持平台多用户认证体系，支持团队协同使用
4、良好的隐匿性，包括但不限于自定义隐藏系统登录地址，以及提供隐匿性部署教程
5、强大的自定义组件，支持自定义开发组件，允许用户根据场景需求开发适合自己的平台组件
6、自定义消息通知接口，除常规的邮件通知以及OPENApi接口外，允许用户自定义消息通知接口，支持与自动化扫描工具进行能力打通

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
