### ISSUE TITLE
[项目申请]: murphysec

### ISSUE THREAD

**Issue by Claire887** [knownsec/404StarLink#79]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

murphysec

### 项目地址

https://github.com/murphysecurity/murphysec

### 项目简介

- 专业的软件成分分析（SCA）
- 许可证合规评估
- 代码漏洞检测
- 全准快的漏洞知识库

### 项目亮点

- 低成本接入开发流程：可以快速集成到 DevOps 的各个流程中
- 项目依赖信息分析：支持分析项目使用的依赖信息，包含直接依赖和间接依赖
- 支持语言丰富：Java、Javascript、Golang、Python等

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。

**Comment by C4skg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近学习繁忙，待有空时将会回复，敬请谅解！
