### ISSUE TITLE
[项目申请]: ENScanGo

### ISSUE THREAD

**Issue by keac** [knownsec/404StarLink#81]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

ENScanGo

### 项目地址

https://github.com/wgpsec/ENScan_GO

### 项目简介

一款基于各大企业信息API的工具，解决在遇到的各种针对国内企业信息收集难题。一键收集控股公司ICP备案、APP、小程序、微信公众号等信息聚合导出。

### 项目亮点

- 基于爱企查、天眼查、七麦数据、酷安市场、站长之家等API进行快速信息收集
- 可以通过公司名称获取到公司子公司、占股公司ICP备案信息、微博、ICP备案、APP、微信公众号 方便进行快速利用

**Comment by Knownsec404team** [comment]
项目很赞哦，请添加下运营：ks404team，便于沟通以及推进项目[加入流程](https://github.com/knownsec/404StarLink2.0-Galaxy#%E5%8A%A0%E5%85%A5join)。
