### ISSUE TITLE
[项目申请]: HummerRisk

### ISSUE THREAD

**Issue by harris1943** [knownsec/404StarLink#85]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

HummerRisk

### 项目地址

https://github.com/HummerRisk/HummerRisk

### 项目简介

HummerRisk 是开源的云原生安全平台，以非侵入的方式解决云原生的安全和治理问题。核心能力包括混合云的安全治理和K8S容器云安全检测。

### 项目亮点

混合云安全治理：
支持全面: 支持的几乎所有公有云，包括：阿里云、腾讯云、华为云、火山引擎、百度云、青云、UCloud、Amazon Web Services、Microsoft Azure、Google Cloud，支持的私有云包括：OpenStack、VMware vSphere，并还在不断的扩充支持的范围；
容易上手: 只需绑定云账号，就可以一键执行检测；
灵活便捷: 多种维度查看检测结果，根据需求任务编排；
开箱即用: 内置大量规则，并且不断迭代新增。用户可以按需自定义规则。

云原生安全检测:
兼容性: 支持多种 K8s 发行版；
独立性: 中立产品，客观检测；
可靠性: 急速响应，快速准确；
无侵入：无侵入式检测。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
