### ISSUE TITLE
[项目申请]:  Vesta 云原生安全检查框架

### ISSUE THREAD

**Issue by christasa** [knownsec/404StarLink#91]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

vesta

### 项目地址

https://github.com/kvesta/vesta

### 项目简介

vesta是一款集容器扫描，Docker和Kubernetes配置基线检查于一身的工具。检查内容包括镜像或容器中包含漏洞版本的组件，Docker以及Kubernetes的危险配置

### 项目亮点

- 除去基本使用apt安装的软件之外还能对python使用pip安装的包模块和部分node使用npm安装的模块进行检测
- 不再需要配置复杂的环境，使用`go build`构建或者从releases内下载编译包及可以使用，方便快捷
- 多操作系统兼容，能够在Windows、Linux、macOS等系统上使用
- Docker和Kubernetes基线配置检查针对目前已知的攻击方法进行检测，同时后续会从BlackHat、Defcon、KubeCon等议题中寻找检查的方法

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
