### ISSUE TITLE
[项目申请]: 

### ISSUE THREAD

**Issue by Bywalks** [knownsec/404StarLink#93]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

DarkAngel

### 项目地址

https://github.com/Bywalks/DarkAngel

### 项目简介

DarkAngel 是一款全自动白帽漏洞扫描器，从hackerone、bugcrowd资产监听到漏洞报告生成、企业微信通知。

### 项目亮点

1、国内唯一的自动扫国外平台的白帽扫描器框架；
2、支持hackerone自动资产监听、bugcrowd自动资产监听；
3、支持自定义资产添加、子域名扫描、网站指纹识别、漏洞主被动扫描功能；
4、漏洞报告自动生成，且支持自定义漏洞模板，并按照模板格式生成漏洞报告；
5、通过企业微信实时通知扫描进度，扫描结果；
6、EK架构前端显示扫描结果，对大数据支持较好，且便于筛选；

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
