### ISSUE TITLE
[项目申请]: FridaRpcTool

### ISSUE THREAD

**Issue by Yuuu99** [knownsec/404StarLink#94]
### 基本要求

- [X] 1. 项目完全开源并遵守开源协议
- [X] 2. 项目提供README等项目描述
- [X] 3. 项目属于计算机安全范畴
- [X] 4. 项目具备一定的实用价值
- [X] 5. 项目不包含恶意功能或源码
- [X] 6. 项目将会积极维护

### 项目名称

FridaRpcTool

### 项目地址

https://github.com/Yuuu99/FridaRpcTool

### 项目简介

FridaRpcTool 是一款基于 BurpSuite Java API 开发的辅助型插件，该插件主要用于对 App 请求/响应数据包中的字段进行便捷加密/解密操作，从而辅助安全从业人员进行安全检测。

### 项目亮点

通过 Frida RPC 算法转发来解决安全检测过程中加密或签名保护的问题。该方法简单便捷，同时插件提供了模式选择、域名过滤、自动 URL 解码、JSON 数据解析等实用功能，帮助安全从业者提高安全检测效率。

**Comment by Knownsec404team** [comment]
您好，感谢投稿。项目未通过404星链计划技术评审环节，期待项目后续的更新和迭代，随时欢迎再次投稿，谢谢！
