### ISSUE TITLE
Contribute  404StarLink-wiki  web 

### ISSUE THREAD

**Issue by chenGit1763113879QQ** [knownsec/404StarLink#97]
你好，最近利用贵仓库的知识库做了一个介绍网站 [404StarLink-wiki](https://chengit1763113879qq.github.io/404StarLink-wiki/#/)，如果你觉得有用可以fork me 或者 [buy a coffee for me](https://boxtrade.github.io/donate/README) ! 如果需要帮助，可以直接在仓库下留言。

Hello, recently used your repository's knowledge base to make an introduction site [404StarLink-wiki](https://chengit1763113879qq.github.io/404StarLink-wiki/#/), if you find it useful you can fork me or [buy a coffee for me]( https://boxtrade.github.io/donate/README) ! If you need help, you can leave a message directly under the repository.

**Comment by 5ky1s61ue** [comment]
您好，您的邮件我已收到，我会尽快阅读，谢谢！
